### ISSUE TITLE
Mlflow and k8s from bitnami (2.18.0)

### ISSUE THREAD

**Issue by DaniilAnd** [mlflow-oidc/mlflow-oidc-auth#65]
Hi! I use mlflow k8s from bitnami (2.18.0-debian-12-r0),
image:
  registry: docker.io
  repository: bitnami/mlflow
  tag: 2.18.0-debian-12-r0

and i rebuild Dockerfile (screenshot 1).
After i add extraenvs in helm chart (screenshot 2) and install new version with plugin OIDC, but mlflow running with error from sqlalchemy (screenshot 3), I also added enable auth (screenshot 4).

Could there be a conflict between the first and fourth screenshot ?

![1](https://github.com/user-attachments/assets/75b67802-67aa-49a1-a6a7-df47fd261b50)
![2](https://github.com/user-attachments/assets/0c8e92c1-d451-4403-ba68-85437a55846a)
![3](https://github.com/user-attachments/assets/b53b00c7-3e14-48e3-956a-a1b4e150b2b5)
![4](https://github.com/user-attachments/assets/8581a3a2-2df0-4b60-9a5b-21391d6f807f)
)

**Comment by kharkevich** [comment]
Hello.
You need to configure databases for both the store and the users.
Regarding the Bitnami image, I have no information about its compatibility or configuration. It would be better to contact them directly.

**Comment by DaniilAnd** [comment]
@kharkevich Hi! I use for users external database. Can I take out the store and add external storе ?

**Comment by ion-elgreco** [comment]
The bitnami chart is compatible, I have it working

**Comment by DaniilAnd** [comment]
@ion-elgreco Hi! Are you using the Entry ID cloud or a local ADFS ?

**Comment by DaniilAnd** [comment]
![image](https://github.com/user-attachments/assets/f77fd107-30b1-4171-96fc-85d1764c5c5a)
This answer from ADFS

**Comment by rojo1997** [comment]
@ion-elgreco can you share an example of a values.yaml? Thanks in advance

**Comment by ion-elgreco** [comment]
@rojo1997 Here is the bitnami values.yaml
```yaml
tracking:
  enabled: true
  auth:
    enabled: false
  command: []
  args: []
  extraArgs:
    - --app-name=oidc-auth
  extraEnvVars:
    - name: OIDC_CLIENT_ID
      value: -
    - name: OIDC_DISCOVERY_URL
      value: "-/.well-known/openid-configuration"
    - name: OIDC_REDIRECT_URI
      value: "-/callback"
    - name: OIDC_PROVIDER_DISPLAY_NAME
      value: "Login with Keycloak"
    - name: OIDC_SCOPE
      value: "openid email profile"
    - name: OAUTHLIB_INSECURE_TRANSPORT
      value: "1"
    - name: OIDC_ADMIN_GROUP_NAME
      value: "admin-mlflow"
    - name: OIDC_GROUP_NAME
      value: "users-mlflow"
    - name: REQUESTS_CA_BUNDLE
      value: "/usr/local/share/ca-certificates/bundle.crt"

extraDeploy:
  # Create secret for mlflow deployment
  - apiVersion: v1
    kind: Secret
    metadata:
      name: mlflow-secrets
    stringData:
      AZURE_STORAGE_ACCESS_KEY:
      OIDC_CLIENT_SECRET:
      OIDC_USERS_DB_URI: 
```
And then custom image:


```docker
ARG VERSION
FROM docker.io/bitnami/mlflow:$VERSION
# RUN pip install mlflow-oidc-auth[full]
COPY mlflow_oidc_auth-3.1.1-py3-none-any.whl /tmp/mlflow_oidc_auth-3.1.1-py3-none-any.whl

USER root
RUN update-ca-certificates
RUN pip install /tmp/mlflow_oidc_auth-3.1.1-py3-none-any.whl[full]
# Create a writable directory for flask_session
RUN mkdir -p /tmp/flask_session
RUN chmod -R 777 /tmp/flask_session

# Set the environment variable for the writable directory
ENV SESSION_FILE_DIR=/tmp/flask_session

# Switch back to the original user
USER 1001

# Set the working directory to the writable directory
WORKDIR /opt/bitnami/mlflow
```

**Comment by ion-elgreco** [comment]
I forgot to mention where the ca-bundle.crt comes from, it's a configmap that we mount, using `trust-manager` which bundles some private certs and public ca certs into one. So `update-ca-certifiactes` will probably install this bundle in the system chain so that mlflow-oidc-auth can properly resolve tls certs

```yaml
  extraVolumes:
    - name: trust-bundle-volume
      configMap:
        name: trust-bundle-default
  extraVolumeMounts:
    - name: trust-bundle-volume
      mountPath: /usr/local/share/ca-certificates/bundle.crt
      subPath: trust-bundle-default.pem
```
